services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wc26_prediction_app
    restart: unless-stopped
    ports:
      - "4000:3000"
    env_file:
      - .env
    volumes:
      - ./prisma:/app/prisma
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_TELEMETRY_DISABLED: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
